#!/usr/bin/env bash

wallpaper_dir="$HOME/pix/wallpapers"
lightmode_lock="$HOME/.cache/lightmode"
lightmode="$(cat ${lightmode_lock})"

#hellwal_args=""
hellwal_args="--neon-mode"

if [ "$1" == "toggle" ]; then
  [[ $lightmode == "1" ]] && lightmode=0 || lightmode=1
  echo $lightmode > $lightmode_lock
fi

if [ "$1" == "theme" ]; then
    theme="$2"
fi

# Fetch colors
source ~/.cache/hellwal/variables.sh

# Randomize new wallpaper or change to light mode
if [ ! -z "$2" ]; then
  if [ "$lightmode" == "1" ]; then
    hellwal -t "$2" "-l" $hellwal_args
    waybar_swapcolors
    firefox_swapcolors
  else
    hellwal -t "$2" "-d" $hellwal_args
    firefox_swapcolors
  fi
else
  if [ ! -z "$1" ]; then
      if [ "$lightmode" == "1" ]; then
          hellwal -m -i "$wallpaper" "-l" $hellwal_args
          waybar_swapcolors
          firefox_swapcolors
      else
          hellwal -m -i "$wallpaper" "-d" $hellwal_args
          firefox_swapcolors
      fi
  else 
      if [ "$lightmode" == "1" ]; then
          hellwal -m -i "$(randomize_unique_wallpaper ${wallpaper_dir})" -l $hellwal_args
          waybar_swapcolors
          firefox_swapcolors
      else
          hellwal -m -i "$(randomize_unique_wallpaper ${wallpaper_dir})" -d $hellwal_args
      fi
  fi
fi

# Fetch colors
source ~/.cache/hellwal/variables.sh

# Bar
waybar_reset &

# HellWM
/home/danihek/hellwm/hellcli reload

# Wallpaper
swww img "$wallpaper" -t random --transition-step 1 --transition-duration 0.4 --transition-fps 60

# Rofi
cp ~/.cache/hellwal/rofi.rasi ~/.config/rofi/config.rasi

# Obsidian
cp ~/.cache/hellwal/obsidian-theme.css ~/dox/school-notes/.obsidian/themes/Hellwal/theme.css

# Discord
themecord

# Firefox
cp ~/.cache/hellwal/pywalfox.json ~/.cache/wal/colors.json
pywalfox update
